export const PROFILE_LOADING_STATE = 'PROFILE_LOADING_STATE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const CHANGE_ARTIST_DATE_RANGE = 'CHANGE_ARTIST_DATE_RANGE';
export const CHANGE_ALBUM_DATE_RANGE = 'CHANGE_ALBUM_DATE_RANGE';
export const CHANGE_GENRE_DATE_RANGE = 'CHANGE_GENRE_DATE_RANGE';
export const CHANGE_TRACK_DATE_RANGE = 'CHANGE_TRACK_DATE_RANGE';

export const TOP_ARTISTS_LOADING_STATE = 'TOP_ARTISTS_LOADING_STATE';
export const TOP_ARTISTS_ERROR = 'TOP_ARTISTS_ERROR';
export const GET_TOP_ARTISTS_ALL_TIME_SUCCESS =
  'GET_TOP_ARTISTS_ALL_TIME_SUCCESS';
export const GET_TOP_ARTISTS_HALF_YEAR_SUCCESS =
  'GET_TOP_ARTISTS_HALF_YEAR_SUCCESS';
export const GET_TOP_ARTISTS_MONTH_SUCCESS = 'GET_TOP_ARTISTS_MONTH_SUCCESS';

export const TOP_TRACKS_LOADING_STATE = 'TOP_TRACKS_LOADING_STATE';
export const TOP_TRACKS_ERROR = 'TOP_TRACKS_ERROR';
export const GET_TOP_TRACKS_ALL_TIME_SUCCESS =
  'GET_TOP_TRACKS_ALL_TIME_SUCCESS';
export const GET_TOP_TRACKS_HALF_YEAR_SUCCESS =
  'GET_TOP_TRACKS_HALF_YEAR_SUCCESS';
export const GET_TOP_TRACKS_MONTH_SUCCESS = 'GET_TOP_TRACKS_MONTH_SUCCESS';

export const RECENTLY_PLAYED_LOADING_STATE = 'RECENTLY_PLAYED_LOADING_STATE';
export const GET_RECENTLY_PLAYED_SUCCESS = 'GET_RECENTLY_PLAYED_SUCCESS';
export const GET_RECENTLY_PLAYED_ERROR = 'GET_RECENTLY_PLAYED_ERROR';

export const SET_SELECTED_TRACK = 'SET_SELECTED_TRACK';

export const TRACK_LOADING_STATE = 'TRACK_LOADING_STATE';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';
export const GET_TRACK_ERROR = 'GET_TRACK_ERROR';
