export const PROFILE_LOADING_STATE = 'PROFILE_LOADING_STATE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE';
export const CHANGE_ARTIST_DATE_RANGE = 'CHANGE_ARTIST_DATE_RANGE';

export const TOP_ARTISTS_LOADING_STATE = 'TOP_ARTISTS_LOADING_STATE';
export const GET_TOP_ARTISTS_ALL_TIME_SUCCESS =
  'GET_TOP_ARTISTS_ALL_TIME_SUCCESS';
export const GET_TOP_ARTISTS_ALL_TIME_ERROR = 'GET_TOP_ARTISTS_ALL_TIME_ERROR';
export const GET_TOP_ARTISTS_HALF_YEAR_SUCCESS =
  'GET_TOP_ARTISTS_HALF_YEAR_SUCCESS';
export const GET_TOP_ARTISTS_HALF_YEAR_ERROR =
  'GET_TOP_ARTISTS_HALF_YEAR_ERROR';
export const GET_TOP_ARTISTS_MONTH_SUCCESS = 'GET_TOP_ARTISTS_MONTH_SUCCESS';
export const GET_TOP_ARTISTS_MONTH_ERROR = 'GET_TOP_ARTISTS_MONTH_ERROR';

export const TOP_TRACKS_LOADING_STATE = 'TOP_TRACKS_LOADING_STATE';
export const GET_TOP_TRACKS_ALL_TIME_SUCCESS =
  'GET_TOP_TRACKS_ALL_TIME_SUCCESS';
export const GET_TOP_TRACKS_ALL_TIME_ERROR = 'GET_TOP_TRACKS_ALL_TIME_ERROR';
export const GET_TOP_TRACKS_HALF_YEAR_SUCCESS =
  'GET_TOP_TRACKS_HALF_YEAR_SUCCESS';
export const GET_TOP_TRACKS_HALF_YEAR_ERROR = 'GET_TOP_TRACKS_HALF_YEAR_ERROR';
export const GET_TOP_TRACKS_MONTH_SUCCESS = 'GET_TOP_TRACKS_MONTH_SUCCESS';
export const GET_TOP_TRACKS_MONTH_ERROR = 'GET_TOP_TRACKS_MONTH_ERROR';
